// ==============================================================================
// src/lib/email/templates/sla-milestone.ts
// Responsive HTML Email Template: SLA Milestone Early Warning & Breach Alert
// ==============================================================================

import { SlaMilestoneTemplateData } from '../types';

export function renderSlaMilestoneEmail(data: SlaMilestoneTemplateData): { subject: string; html: string; text: string } {
  const statusPrefix = data.isBreached ? 'CRITICAL SLA BREACH' : 'SLA Milestone Warning';
  const subject = `[${statusPrefix}] ${data.milestoneTitle} (${data.projectName})`;

  const text = `
SLA ALERT: ${statusPrefix}

Milestone: ${data.milestoneTitle}
Project: ${data.projectName}
Target Date: ${data.targetDate}
Status: ${data.isBreached ? 'DEADLINE BREACHED' : `${data.hoursRemaining} hours remaining`}

Please take immediate corrective action:
${data.actionUrl}
`;

  const bannerColor = data.isBreached ? '#dc2626' : '#d97706';

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0f172a; margin: 0; padding: 0; color: #f8fafc; }
    .container { max-width: 600px; margin: 40px auto; background: #1e293b; border-radius: 12px; border: 1px solid #334155; overflow: hidden; }
    .alert-banner { background: ${bannerColor}; color: #ffffff; padding: 24px; text-align: center; font-weight: 700; font-size: 18px; letter-spacing: 0.05em; }
    .body { padding: 32px 24px; }
    .milestone-box { background: #0f172a; border-left: 4px solid ${bannerColor}; border-radius: 0 8px 8px 0; padding: 20px; margin: 20px 0; }
    .btn { display: inline-block; background-color: ${bannerColor}; color: #ffffff !important; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 700; font-size: 15px; }
    .footer { background: #0f172a; padding: 18px 24px; text-align: center; font-size: 12px; color: #64748b; }
  </style>
</head>
<body>
  <div class="container">
    <div class="alert-banner">
      ${data.isBreached ? '⚠️ CRITICAL SLA THRESHOLD BREACHED' : '⏳ UPCOMING SLA DEADLINE REMINDER'}
    </div>
    <div class="body">
      <h2 style="color: #ffffff; margin-top: 0; font-size: 20px;">Milestone Schedule Escalation</h2>
      <p style="color: #cbd5e1; font-size: 15px; line-height: 1.6;">
        Attention ${data.recipientName}, the critical path milestone below requires supervisory review:
      </p>

      <div class="milestone-box">
        <h3 style="margin: 0 0 8px; color: #f8fafc; font-size: 18px;">${data.milestoneTitle}</h3>
        <p style="margin: 0 0 12px; color: #94a3b8; font-size: 14px;">Project: <strong>${data.projectName}</strong></p>
        <div style="font-size: 14px; color: ${data.isBreached ? '#fca5a5' : '#fde68a'}; font-weight: 600;">
          ${data.isBreached ? 'Status: Overdue past SLA commitment date' : `Status: Approaching deadline with ${data.hoursRemaining} hours remaining`}
        </div>
        <div style="font-size: 13px; color: #94a3b8; margin-top: 4px;">Target Completion: ${data.targetDate}</div>
      </div>

      <div style="text-align: center; margin: 32px 0 16px;">
        <a href="${data.actionUrl}" class="btn" target="_blank">Review Critical Path in CPM Engine</a>
      </div>
    </div>
    <div class="footer">
      Automated escalation generated by Enterprise PMS Background SLA Monitor.
    </div>
  </div>
</body>
</html>
`;

  return { subject, html, text };
}
